// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconIcRoundDiscord: typeof import('~icons/ic/round-discord')['default']
    IconLucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    IconLucideBell: typeof import('~icons/lucide/bell')['default']
    IconLucideCode2: typeof import('~icons/lucide/code2')['default']
    IconLucideCrown: typeof import('~icons/lucide/crown')['default']
    IconLucideGithub: typeof import('~icons/lucide/github')['default']
    IconLucideHeart: typeof import('~icons/lucide/heart')['default']
    IconLucideLanguages: typeof import('~icons/lucide/languages')['default']
    IconLucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucidePencil: typeof import('~icons/lucide/pencil')['default']
    IconLucideSmartphone: typeof import('~icons/lucide/smartphone')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconLucideTimerReset: typeof import('~icons/lucide/timer-reset')['default']
    IconLucideTrendingUp: typeof import('~icons/lucide/trending-up')['default']
    IconLucideTwitter: typeof import('~icons/lucide/twitter')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    IconLucideUsers: typeof import('~icons/lucide/users')['default']
    IconMdiCardsOutline: typeof import('~icons/mdi/cards-outline')['default']
    IconMdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
