// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconIcRoundDiscord: typeof import('~icons/ic/round-discord')['default']
    IconLucideBook: typeof import('~icons/lucide/book')['default']
    IconLucideCode2: typeof import('~icons/lucide/code2')['default']
    IconLucideComponent: typeof import('~icons/lucide/component')['default']
    IconLucideGithub: typeof import('~icons/lucide/github')['default']
    IconLucideHome: typeof import('~icons/lucide/home')['default']
    IconLucideLanguages: typeof import('~icons/lucide/languages')['default']
    IconLucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    IconLucidePlay: typeof import('~icons/lucide/play')['default']
    IconLucideTwitter: typeof import('~icons/lucide/twitter')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    IconLucideUsers: typeof import('~icons/lucide/users')['default']
    IconLucideZap: typeof import('~icons/lucide/zap')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
