files:
  - source: /public/locales/en/common.json
    translation: /public/locales/%two_letters_code%/common.json
  - source: /public/locales/en/discover.json
    translation: /public/locales/%two_letters_code%/discover.json
